meta_title: "VAXT présente TROU"
meta_description: " VERNISSAGE LE 11 JANVIER | VAXT présente TROU, l'exposition qui a besoin de l'extérieur pour exister. Du 11 janvier au 13 avril 2019."
meta_image: "opengraph.jpg" # should exist in `app/assets/images/`
